package com.example.memorygame;

import javafx.geometry.Pos;
import javafx.scene.control.Button;
import javafx.scene.layout.*;
import javafx.geometry.Insets;
import javafx.scene.control.Label;
import javafx.scene.image.ImageView;
import javafx.scene.image.Image;


public final class FxmlMemoryGame {
	public MemoryGameController _controller;
	public AnchorPane _view;
	public FxmlMemoryGame() {
		_controller = new MemoryGameController();
		AnchorPane ctrl_1 = new AnchorPane();
		ctrl_1.setPrefHeight(600.0);
		//ctrl_1.getStylesheets().add(toUrl("styles.css"));
		ctrl_1.setPrefWidth(1000.0);
		VBox ctrl_2 = new VBox();
		ctrl_2.setPrefHeight(650.0);
		AnchorPane.setTopAnchor(ctrl_2, 0.0);
		ctrl_2.setSpacing(20.0);
		ctrl_2.setPrefWidth(1000.0);
		AnchorPane.setRightAnchor(ctrl_2, 0.0);
		AnchorPane.setLeftAnchor(ctrl_2, 0.0);
		ctrl_2.setLayoutX(413.0);
		ctrl_2.setLayoutY(139.0);
		AnchorPane.setBottomAnchor(ctrl_2, 0.0);
		FlowPane imagesFlowPane = new FlowPane();
		_controller.imagesFlowPane = imagesFlowPane;
		imagesFlowPane.setVgap(20.0);
		imagesFlowPane.setAlignment(Pos.CENTER);
		imagesFlowPane.setHgap(20.0);
		ImageView ctrl_3 = new ImageView();
		//ctrl_3.setPickOnBounds(true);
		ctrl_3.setFitWidth(125.0);
		ctrl_3.setFitHeight(205.0);
		ctrl_3.setPreserveRatio(true);
		Image ctrl_4 = new Image(toUrl("images/3_of_hearts.png"));
		ctrl_3.setImage(ctrl_4);
		ImageView ctrl_5 = new ImageView();
		//ctrl_5.setPickOnBounds(true);
		ctrl_5.setFitWidth(125.0);
		ctrl_5.setFitHeight(205.0);
		ctrl_5.setPreserveRatio(true);
		Image ctrl_6 = new Image(toUrl("images/3_of_hearts.png"));
		ctrl_5.setImage(ctrl_6);
		ImageView ctrl_7 = new ImageView();
		//ctrl_7.setPickOnBounds(true);
		ctrl_7.setFitWidth(125.0);
		ctrl_7.setFitHeight(205.0);
		ctrl_7.setPreserveRatio(true);
		Image ctrl_8 = new Image(toUrl("images/3_of_hearts.png"));
		ctrl_7.setImage(ctrl_8);
		ImageView ctrl_9 = new ImageView();
		//ctrl_9.setPickOnBounds(true);
		ctrl_9.setFitWidth(125.0);
		ctrl_9.setFitHeight(205.0);
		ctrl_9.setPreserveRatio(true);
		ctrl_9.setLayoutX(286.0);
		ctrl_9.setLayoutY(10.0);
		Image ctrl_10 = new Image(toUrl("images/3_of_hearts.png"));
		ctrl_9.setImage(ctrl_10);
		ImageView ctrl_11 = new ImageView();
		//ctrl_11.setPickOnBounds(true);
		ctrl_11.setFitWidth(125.0);
		ctrl_11.setFitHeight(205.0);
		ctrl_11.setPreserveRatio(true);
		ctrl_11.setLayoutX(424.0);
		ctrl_11.setLayoutY(10.0);
		Image ctrl_12 = new Image(toUrl("images/3_of_hearts.png"));
		ctrl_11.setImage(ctrl_12);
		ImageView ctrl_13 = new ImageView();
		//ctrl_13.setPickOnBounds(true);
		ctrl_13.setFitWidth(125.0);
		ctrl_13.setFitHeight(205.0);
		ctrl_13.setPreserveRatio(true);
		ctrl_13.setLayoutX(562.0);
		ctrl_13.setLayoutY(10.0);
		Image ctrl_14 = new Image(toUrl("images/3_of_hearts.png"));
		ctrl_13.setImage(ctrl_14);
		ImageView ctrl_15 = new ImageView();
		//ctrl_15.setPickOnBounds(true);
		ctrl_15.setFitWidth(125.0);
		ctrl_15.setFitHeight(205.0);
		ctrl_15.setPreserveRatio(true);
		ctrl_15.setLayoutX(700.0);
		ctrl_15.setLayoutY(10.0);
		Image ctrl_16 = new Image(toUrl("images/3_of_hearts.png"));
		ctrl_15.setImage(ctrl_16);
		ImageView ctrl_17 = new ImageView();
		//ctrl_17.setPickOnBounds(true);
		ctrl_17.setFitWidth(125.0);
		ctrl_17.setFitHeight(205.0);
		ctrl_17.setPreserveRatio(true);
		ctrl_17.setLayoutX(838.0);
		ctrl_17.setLayoutY(10.0);
		Image ctrl_18 = new Image(toUrl("images/3_of_hearts.png"));
		ctrl_17.setImage(ctrl_18);
		ImageView ctrl_19 = new ImageView();
		//ctrl_19.setPickOnBounds(true);
		ctrl_19.setFitWidth(125.0);
		ctrl_19.setFitHeight(205.0);
		ctrl_19.setPreserveRatio(true);
		ctrl_19.setLayoutX(10.0);
		ctrl_19.setLayoutY(210.0);
		Image ctrl_20 = new Image(toUrl("images/3_of_hearts.png"));
		ctrl_19.setImage(ctrl_20);
		ImageView ctrl_21 = new ImageView();
		//ctrl_21.setPickOnBounds(true);
		ctrl_21.setFitWidth(125.0);
		ctrl_21.setFitHeight(205.0);
		ctrl_21.setPreserveRatio(true);
		ctrl_21.setLayoutX(148.0);
		ctrl_21.setLayoutY(210.0);
		Image ctrl_22 = new Image(toUrl("images/3_of_hearts.png"));
		ctrl_21.setImage(ctrl_22);
		ImageView ctrl_23 = new ImageView();
		//ctrl_23.setPickOnBounds(true);
		ctrl_23.setFitWidth(125.0);
		ctrl_23.setFitHeight(205.0);
		ctrl_23.setPreserveRatio(true);
		ctrl_23.setLayoutX(13.0);
		ctrl_23.setLayoutY(10.0);
		Image ctrl_24 = new Image(toUrl("images/3_of_hearts.png"));
		ctrl_23.setImage(ctrl_24);
		ImageView ctrl_25 = new ImageView();
		//ctrl_25.setPickOnBounds(true);
		ctrl_25.setFitWidth(125.0);
		ctrl_25.setFitHeight(205.0);
		ctrl_25.setPreserveRatio(true);
		ctrl_25.setLayoutX(403.0);
		ctrl_25.setLayoutY(560.0);
		Image ctrl_26 = new Image(toUrl("images/3_of_hearts.png"));
		ctrl_25.setImage(ctrl_26);
		imagesFlowPane.getChildren().setAll(ctrl_3, ctrl_5, ctrl_7, ctrl_9, ctrl_11, ctrl_13, ctrl_15, ctrl_17, ctrl_19, ctrl_21, ctrl_23, ctrl_25);
		HBox ctrl_27 = new HBox();
		ctrl_27.setSpacing(125.0);
		ctrl_27.setAlignment(Pos.CENTER);
		GridPane ctrl_28 = new GridPane();
		ColumnConstraints ctrl_29 = new ColumnConstraints();
		ctrl_29.setHgrow(Priority.SOMETIMES);
		ctrl_29.setPrefWidth(147.0);
		ctrl_29.setMinWidth(10.0);
		ctrl_29.setMaxWidth(147.0);
		ColumnConstraints ctrl_30 = new ColumnConstraints();
		ctrl_30.setHgrow(Priority.SOMETIMES);
		ctrl_30.setPrefWidth(53.0);
		ctrl_30.setMinWidth(10.0);
		ctrl_30.setMaxWidth(95.0);
		//ctrl_28.setColumnConstraints(ctrl_29);
		ctrl_28.getColumnConstraints().setAll(ctrl_29);
		RowConstraints ctrl_31 = new RowConstraints();
		ctrl_31.setMinHeight(10.0);
		ctrl_31.setPrefHeight(30.0);
		ctrl_31.setVgrow(Priority.SOMETIMES);
		RowConstraints ctrl_32 = new RowConstraints();
		ctrl_32.setMinHeight(10.0);
		ctrl_32.setPrefHeight(30.0);
		ctrl_32.setVgrow(Priority.SOMETIMES);
		//ctrl_28.setRowConstraints(ctrl_31);
		ctrl_28.getRowConstraints().setAll(ctrl_31);
		Label ctrl_33 = new Label();
		ctrl_33.setTextFill(null);
		ctrl_33.setText("Guesses:");
		Label ctrl_34 = new Label();
		ctrl_34.setTextFill(null);
		GridPane.setRowIndex(ctrl_34, 1);
		ctrl_34.setText("Correct:");
		Label guessLabel = new Label();
		guessLabel.setTextFill(null);
		_controller.guessLabel = guessLabel;
		GridPane.setColumnIndex(guessLabel, 1);
		guessLabel.setText("0");
		Label correctGuessesLabel = new Label();
		correctGuessesLabel.setTextFill(null);
		_controller.correctGuessesLabel = correctGuessesLabel;
		GridPane.setColumnIndex(correctGuessesLabel, 1);
		GridPane.setRowIndex(correctGuessesLabel, 1);
		correctGuessesLabel.setText("0");
		//ctrl_28.setChildren(ctrl_33);
		ctrl_28.getChildren().setAll(ctrl_33, ctrl_34, guessLabel, correctGuessesLabel);
		Button ctrl_35 = new Button();
		ctrl_35.setBackground(null);
		ctrl_35.setBorder(null);
		ctrl_35.setOnAction(e -> _controller.playAgain());
		ctrl_35.setPrefWidth(200.0);
		ctrl_35.setText("Play Again");
		//ctrl_35.setMnemonicParsing(false);
		Button ctrl_36 = new Button();
		ctrl_36.setBackground(null);
		ctrl_36.setBorder(null);
		ctrl_36.setOnAction(_controller::playWar);
		ctrl_36.setPrefWidth(200.0);
		ctrl_36.setText("War Game");
		//ctrl_36.setMnemonicParsing(false);
		ctrl_27.getChildren().setAll(ctrl_28, ctrl_35, ctrl_36);
		ctrl_2.getChildren().setAll(imagesFlowPane, ctrl_27);
		Insets ctrl_37 = new Insets(20.0, 20.0, 20.0, 20.0);
		ctrl_2.setPadding(ctrl_37);
		ctrl_1.getChildren().setAll(ctrl_2);
		_view = ctrl_1;

		_controller.initialize(null, null);
	}

	private static String toUrl(String path) {
		return WebFXUtil.toUrl(path);
	}
}
